import { z } from "zod";

/**** Simulation configuration YAML format validation ****/
/**** global ****/

// The `systemGeneratedFields` array contains fields that are automatically 
// generated by the system and should not be provided by users.
const systemGeneratedFields = [
  'uniqueServiceName',
  'uniqueEndpointName',
] as const;

export const systemGeneratedFieldsSuperRefine = <T extends object>() => (data: T, ctx: z.RefinementCtx) => {
  for (const field of systemGeneratedFields) {
    if ((data as any)[field] !== undefined) {
      ctx.addIssue({
        code: "custom",
message: `${field} is a system-generated field. It should not be provided.`,
        path: [field],
      });
    }
  }
};


// endpointId
export const endpointIdSchema = z.preprocess(
  (val) => (typeof val === "number" ? val.toString() : val),
  z.string()
    .refine(s => s.trim().length > 0, { message: "endpointId cannot be empty." })
    .transform(s => s.trim())
);


// version
export const versionSchema = z.preprocess(
  (val) => (typeof val === "number" ? val.toString() : val),
  z.string()
    .refine(s => s.trim().length > 0, { message: "version cannot be empty." })
    .transform(s => s.trim())
);

