//Context type used during validation and preprocessing of the simulation configuration.
export type TServiceInfoDefinitionContext = {
  // key: UniqueServiceName, 
  // value: Set of endpointId (all endpointId under the service)
  uniqueServiceNameToEndpointIdMap: Map<string, Set<string>>;

  // UniqueServiceNames defined in the services info 
  // (UniqueServiceNames is generated by the system)
  allDefinedUniqueServiceNames: Set<string>;

  // key: endpointId
  // value: UniqueEndpointName
  endpointIdToUniqueNameMap: Map<string, string>;

  // EndpointIds defined in the services info
  allDefinedEndpointIds: Set<string>;
};