apiVersion: v1
kind: Service
metadata:
  name: mongo-simulator
  namespace: kmamiz-system
spec:
  type: NodePort
  selector:
    app: mongo-simulator
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-simulator
  namespace: kmamiz-system
spec:
  selector:
    matchLabels:
      app: mongo-simulator
  serviceName: mongo-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-simulator
    spec:
      containers:
        - name: mongo-simulator
          image: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: "simulator"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-simulator-pv
              mountPath: /data/db
            - name: mongo-simulator-init
              mountPath: "/docker-entrypoint-initdb.d/mongo-simulator-init.js"
              subPath: "mongo-simulator-init.js"
      volumes:
        - name: mongo-simulator-init
          configMap:
            name: mongo-simulator-init
  volumeClaimTemplates:
    - metadata:
        name: mongo-simulator-pv
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 2Gi
