apiVersion: v1
kind: ConfigMap
metadata:
  name: kmamiz-global-env
  namespace: kmamiz-system
data:
  PORT: "3000" 
  ZIPKIN_URL: "http://zipkin.istio-system:9411"
  LOG_LEVEL: "info"
  IS_RUNNING_IN_K8S: "true"
  ENVOY_LOG_LEVEL: "warning" # accept: info | warning | error
  READ_ONLY_MODE: "false"
  ENABLE_TESTING_ENDPOINTS: "true"