apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmamiz
  namespace: kmamiz-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kmamiz
    spec:
      serviceAccountName: kmamiz-reader
      containers:
        - name: kmamiz
          image: "wys899195/kmamiz:latest"
          ports:
            - containerPort: 3000
          envFrom:
            # kmamiz-global-env
            - configMapRef:
                name: kmamiz-global-env
          env:
            - name: SERVICE_PORT # this needs to match port set in Service
              value: "80"
            - name: MONGODB_URI
              value: "{your-mongodb-uri}"
            - name: SIMULATOR_MODE
              value: "false"

            # admin settings
            - name: INACTIVE_ENDPOINT_THRESHOLD # The time threshold for marking a service or endpoints inactive, which affects the DependencyGraph pages.
              value: ""     # 1. Format: "XdYh" (e.g., "3d4h", "10h"), where X = days,Y = hours
                            # 
                            # 2. If you don't want to set it, you can leave it as an empty string, and it will be treated as 0 seconds, meaning it will not affect the dependency graph's display.
            - name: DEPRECATED_ENDPOINT_THRESHOLD # The time threshold for marking a service or endpoints deprecated, which affects the DependencyGraph and Insight pages.
              value: ""     # 1. Format: "XdYh" (e.g., "3d4h", "10h"), where X = days,Y = hours
                            #    
                            # 2. If you don't want to set it, you can leave it as an empty string, and it will be treated as 0 seconds, meaning it will not affect the dependency graph's display.
                            #
                            # 3.(IMPORTANT!) If the value is set, it must be greater than the value of INACTIVE_ENDPOINT_THRESHOLD.
                            #   Otherwise, the 'inactive' nodes will not be displayed in the dependency graph, because the 'deprecated' threshold would be considered before the 'inactive' threshold.
  selector:
    matchLabels:
      app: kmamiz
---
apiVersion: v1
kind: Service
metadata:
  name: kmamiz
  namespace: kmamiz-system
spec:
  type: NodePort
  selector:
    app: kmamiz
  ports:
    - protocol: TCP
      port: 80 # this needs to match SERVICE_PORT
      targetPort: 3000
