apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmamiz-simulator
  namespace: kmamiz-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kmamiz-simulator
    spec:
      serviceAccountName: kmamiz-reader
      containers:
        - name: kmamiz-simulator
          image: "wys899195/kmamiz:latest"
          ports:
            - containerPort: 3000
          envFrom:
            # kmamiz-global-env
            - configMapRef:
                name: kmamiz-global-env
          env:
            - name: SERVICE_PORT # this needs to match port set in Service
              value: "8081"
            - name: MONGODB_URI
              value: "{your-mongodb-uri}"
            - name: SIMULATOR_MODE
              value: "true"
            
  selector:
    matchLabels:
      app: kmamiz-simulator
---
apiVersion: v1
kind: Service
metadata:
  name: kmamiz-simulator
  namespace: kmamiz-system
spec:
  type: NodePort
  selector:
    app: kmamiz-simulator
  ports:
    - protocol: TCP
      port: 8081 # this needs to match SERVICE_PORT
      targetPort: 3000
